// Seed tasks for the "codebase" tier (Path A) of the 3-tier marketplace.
// Bidder receives a snapshot of the demo Todo app, returns a unified diff that
// makes the failing test in __tests__/settings.test.tsx pass.
import { readFileSync, readdirSync, statSync } from "fs";
import { join, relative } from "path";
import type { CodebasePayload, Language, TaskType } from "@/lib/types";

export interface CodebaseSeedTask {
  id: string;
  title: string;
  description: string;
  language: Language;
  task_type: TaskType;
  max_bounty_sats: number;
  deadline_minutes: number;
  payload: () => CodebasePayload;
  // Working unified diff that solves the task. Used as a fallback when LLM
  // generation fails so the demo never stalls.
  reference_solution: string;
}

// Walk the demo codebase and snapshot every file as a context_files entry.
// Skips heavy/irrelevant directories so the payload stays small.
function loadCodebaseFiles(rootDir: string): Array<{ path: string; content: string }> {
  const skip = new Set([
    "node_modules",
    ".next",
    "dist",
    ".git",
    ".turbo",
    "coverage",
  ]);
  const out: Array<{ path: string; content: string }> = [];

  function walk(dir: string) {
    for (const entry of readdirSync(dir)) {
      if (skip.has(entry)) continue;
      const full = join(dir, entry);
      const st = statSync(full);
      if (st.isDirectory()) {
        walk(full);
      } else if (st.isFile()) {
        // Skip the lockfile — it's enormous and not needed by the bidder.
        if (entry === "package-lock.json") continue;
        out.push({
          path: relative(rootDir, full),
          content: readFileSync(full, "utf8"),
        });
      }
    }
  }

  walk(rootDir);
  return out;
}

const TODO_APP_ROOT = join(process.cwd(), "demo-codebases", "todo-app");

// Verified working diff. Generated by:
//   1. add components/DarkModeToggle.tsx (uses useTheme() from ThemeProvider)
//   2. import + render <DarkModeToggle /> in app/settings/page.tsx
//   3. `cd demo-codebases/todo-app && npm test -- --run` => 2 passed.
const DARK_MODE_REFERENCE_DIFF = `--- a/components/DarkModeToggle.tsx
+++ b/components/DarkModeToggle.tsx
@@ -0,0 +1,19 @@
+"use client";
+
+import { useTheme } from "@/components/ThemeProvider";
+
+export function DarkModeToggle() {
+  const { theme, toggleTheme } = useTheme();
+  const isDark = theme === "dark";
+  return (
+    <button
+      type="button"
+      data-testid="dark-mode-toggle"
+      onClick={toggleTheme}
+      aria-pressed={isDark}
+      className="rounded border border-fg/20 px-3 py-2 text-sm hover:bg-fg/5"
+    >
+      {isDark ? "Switch to light mode" : "Switch to dark mode"}
+    </button>
+  );
+}
--- a/app/settings/page.tsx
+++ b/app/settings/page.tsx
@@ -1,6 +1,7 @@
 "use client";

 import Link from "next/link";
+import { DarkModeToggle } from "@/components/DarkModeToggle";

 export default function SettingsPage() {
   return (
@@ -17,7 +18,7 @@
         <p className="text-sm opacity-70">
           Theme preferences will appear here.
         </p>
-        {/* TODO: add a dark mode toggle that uses useTheme() from components/ThemeProvider */}
+        <DarkModeToggle />
       </section>
     </div>
   );
`;

export const CODEBASE_TASKS: CodebaseSeedTask[] = [
  {
    id: "codebase-darkmode",
    title: "Add dark mode toggle to settings page",
    description:
      "The Todo app already has a ThemeProvider with a useTheme() hook, but the Settings page has no UI to switch themes. Add a DarkModeToggle component to app/settings/page.tsx. The button must carry data-testid=\"dark-mode-toggle\" so the existing test in __tests__/settings.test.tsx passes.",
    language: "typescript",
    task_type: "codebase",
    max_bounty_sats: 50_000,
    deadline_minutes: 10,
    payload: (): CodebasePayload => ({
      codebase_id: "todo-app",
      context_files: loadCodebaseFiles(TODO_APP_ROOT),
      test_command: "npm test -- --run",
      task_description:
        "Add a dark mode toggle button to app/settings/page.tsx using the existing useTheme() hook from components/ThemeProvider.tsx. The button must have data-testid=\"dark-mode-toggle\". After your diff is applied, `npm test -- --run` must pass.",
    }),
    reference_solution: DARK_MODE_REFERENCE_DIFF,
  },
];
